### PR TITLE
cleanup + changes from reddit topic (29.06.2016)

### PR DESCRIPTION
**Pull request by vinceblk**

### CODE REVIEW

**Comment by bearsylla** [comment]
I tried to merge it, but i found out that the numbers in "coin specifications" section were not working, thus i reverted it. I am busy lately and doesn't have time to review the problem. Would you mind double check it and let me know?

**Comment by vinceblk** [comment]
I have the mirror of this website on my pc and everything works fine here - its probably some file extension issue. It would be much faster for me to find it, if I would see it online. Could you be able to merge it again and I will try to fix it asap? I will then pull another request.. Thanks

**Comment by bearsylla** [comment]
done. your version is live now. but it says 0% interest, 0% inflation etc

**Comment by bearsylla** [comment]
nevermind. i think i fixed it now

**Comment by vinceblk** [comment]
I can see there are some scripts issues - its not only specification which doesnt work, also news, popup, slider..

**Comment by bearsylla** [comment]
I think i will revert back to 050866753c51059b9cb54a2a4d63d39b0924ad50 first, then we see what we can do from there.

**Comment by vinceblk** [comment]
please leave it merged and  I can sort it out from there.. Its some easy fix - probably 1 line. I will do it in no time. thanks

**Comment by vinceblk** [comment]
ok I got it, basically it was winhttrack fault ;) I will create new pull request in ~15 mins. thanks

**Pull request merged**
